//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartialAndLayoutViews.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int Eno { get; set; }
        public string Ename { get; set; }
        public decimal Salary { get; set; }
        public string Job { get; set; }
        public Nullable<int> DeptID { get; set; }
    }
}
